server:
  port: 8189
  servlet:
    context-path: /tsm
utils:
  cart:
    prefix: tsm
spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./tails;MODE=PostgreSQL
    username: sa
    password:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
logging:
  level:
    ROOT: WARN
